module.exports = function (app) {
    // require('./organizations-e2e')(app);
    // require('./classifications-e2e')(app);
    // require('./userClassificationViewPermission-e2e')(app);
    // // require('./correspondence-sites-e2e')(app);
    // // require('./correspondence-site-types-e2e')(app);
    // // require('./distribution-lists-e2e')(app);
    // require('./roles-e2e')(app);
    // require('./workflow-groups-e2e')(app);
    // require('./application-users-e2e')(app);
    // require('./job-titles-e2e')(app);
    // require('./public-announcements-e2e')(app);
    // require('./private-announcements-e2e')(app);
    // require('./sms-templates-e2e')(app);
    // require('./document-types-e2e')(app);
    // require('./organization-types-e2e')(app);
    // require('./workflow-actions-e2e')(app);
    // require('./user-workflow-actions-e2e')(app);
    // //require('./user-workflow-groups-e2e')(app);
    // require('./global-localization-lookup-e2e')(app);
    // //require('./lookup-e2e')(app);
    // require('./draft-outgoing-e2e')(app);
    // require('./review-outgoing-e2e')(app);
    // require('./send-outgoing-e2e')(app);
    // require('./rejected-outgoing-e2e')(app);
    // require('./prepare-outgoing-e2e')(app);
    // require('./attachment-types-e2e')(app);
    //require('./manage-correspondence-sites-e2e')(app);
};